raw_files:
  feature_files: [[/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/HBLower_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/tile031_3125_11250_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/tile030_10000_5625_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/tile024_10000_3125_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/tile016_0_4375_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/KParadise_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/tile024_10000_4375_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/Waikoloa1_hires_surface.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_features/Kukio1_hires_surface.tif]]
  response_files: [[/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/HBLower_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/tile031_3125_11250_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/tile030_10000_5625_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/tile024_10000_3125_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/tile016_0_4375_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/KParadise_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/tile024_10000_4375_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/Waikoloa1_responses.tif], [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_buildings/Kukio1_responses.tif]]
  boundary_files: [/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/HBLower_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/tile031_3125_11250_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/tile030_10000_5625_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/tile024_10000_3125_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/tile016_0_4375_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/KParadise_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/tile024_10000_4375_boundary.shp, /data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/Waikoloa1_boundary.shp,/data/gdcsdata/HawaiiMapping/ProjectFiles/Rachel/labeled_region_boundaries/Kukio1_boundary.shp]
  feature_data_type: ['R']
  response_data_type: ['C']
  feature_nodata_value: -9999
  response_nodata_value: -9999
  boundary_bad_value: 0
  ignore_projections: false
data_build:
  dir_out: ./data_out
  filename_prefix_out: 'munged_data'
  network_category: FCN
  random_seed: 1
  max_samples: 150000
  max_built_data_gb: 40
  number_folds: 10
  validation_fold: 0
  test_fold: None
  window_radius: 32
  loss_window_radius: 16
  feature_mean_centering: True
  feature_nodata_maximum_fraction: 0.2
  response_min_value: null
  response_max_value: null
  response_background_values: None
data_samples:
  batch_size: 32
  feature_scaler_names: ['NullScaler']
  response_scaler_names: ['NullScaler']
  feature_nodata_encoding: -10.0
model_training:
  dir_out: ./model_out
  verbosity: 2
  assert_gpu: true
  architecture_name: unet
  loss_metric: cc
  max_epochs: 500
  optimizer: adam
  weighted: true
architecture:
  block_structure: [4, 4]
  filters: 6
  kernel_size: [3, 3]
  min_conv_width: 8
  n_classes: 2
  output_activation: softmax
  padding: same
  pool_size: [2, 2]
  use_batch_norm: true
  use_growth: false
  use_initial_colorspace_transformation_layer: false
model_reporting:
  max_pages_per_figure: 1
  max_samples_per_page: 20
  max_features_per_page: 10
  max_responses_per_page: 10
  network_progression_max_pages: 2
  network_progression_max_filters: 10
  network_progression_show_full: true
  network_progression_show_compact: false
callback_general:
  checkpoint_periods: 5
  use_terminate_on_nan: true
callback_tensorboard:
  use_callback: true
  update_freq: epoch
  histogram_freq: 0
  write_graph: true
  write_grads: false
  write_images: true
callback_early_stopping:
  use_callback: true
  min_delta: 0.0001
  patience: 10
callback_reduced_learning_rate:
  use_callback: true
  factor: 0.5
  min_delta: 0.0001
  patience: 10
